version: '3.8'

services:
  # API Service
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    image: "nhatpun/credit-risk-api:latest"
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_DIR=/app/models
      - DEBUG=true
    deploy:
    networks:
      - credit-risk-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    #

  # Streamlit App
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    image: "nhatpun/credit-risk-app:latest"
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
      - DEBUG=true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - credit-risk-network
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy

networks:
  credit-risk-network:
    driver: bridge 