version: '3.8'

services:
  api:
    build: .
    image: credit-default-prediction:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./model/saved_models:/app/model/saved_models
    networks:
      - credit-network

networks:
  credit-network:
    driver: overlay 